name: Release Branch Workflow

on:
  push:
    branches: [ 'release/**' ]
  pull_request:
    branches: [ 'release/**' ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    env:
      MONGODB_DB_NAME: ${{ vars.MONGODB_DB_NAME }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      AUTH_GOOGLE_ID: ${{ secrets.AUTH_GOOGLE_ID }}
      NEXT_PUBLIC_REOWN_PROJECT_ID: ${{ vars.NEXT_PUBLIC_REOWN_PROJECT_ID }}
      NEXT_PUBLIC_WC_PROJECT_ID: ${{ vars.NEXT_PUBLIC_WC_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: |
          npm ci
          npm run build
          
  create-pre-release:
    needs: test-and-build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Pre-release
        run: echo "Creating pre-release"
